[tool.poetry]
name = "forecast"
version = "0.1.0"
description = "Generic forecast utilities"
authors = ["Tyler Matteson <tyler@agritheory.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
attrs = "^19.3.0"
numpy = "^1.19.1"
pandas = "^1.1.0"
scipy = "^1.5.2"

[tool.poetry.dev-dependencies]
nbdev = "^0.2.20"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
matplotlib = "^3.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
